drop table IF EXISTS users CASCADE;
drop table IF EXISTS categories CASCADE;
drop table IF EXISTS events CASCADE;
drop table IF EXISTS locations CASCADE;

create table if not exists users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UQ_NAME_CATEGORY UNIQUE (name)
);

create table if not exists locations (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     lat float NOT NULL,
     lon float NOT NULL,
     CONSTRAINT loc_pk PRIMARY KEY (id)
);

create table if not exists events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY not null constraint events_pk primary key ,
    annotation VARCHAR(2000) NOT NULL,
    title VARCHAR(512) NOT NULL,
    category_id bigint not null constraint event_category_id_fk references categories
        on update cascade on delete cascade,
    description  VARCHAR(7000) NOT NULL,
    paid boolean not null,
    created_on timestamp without time zone,
    event_date timestamp without time zone,
    user_id bigint not null constraint event_user_id_fk references users
        on update cascade on delete cascade,
    participant_limit INT NOT NULL,
    request_Moderation boolean NOT NULL,
    published_On timestamp without time zone,
    loc_id bigint not null constraint event_location_id_fk references locations
        on update cascade on delete cascade,
    state varchar(512) not null
);
