drop table IF EXISTS stats CASCADE;

create TABLE IF NOT EXISTS stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  app VARCHAR(255) NOT NULL,
  uri VARCHAR(512) NOT NULL,
  ip VARCHAR(512) NOT NULL,
  created timestamp without time zone
);